apiVersion : apps/v1
kind: Deployment
metadata:
  name: nlp-spacy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp-spacy 
  template:
    metadata:
      labels:
        app: nlp-spacy 
    spec:
      containers:
        - name: nlp-spacy 
          image: services.azurecr.io/nlp-spacy
          ports:
          - containerPort: 8990